name: Deployment on GitHub Pages

on:
  push:
    branches: [ "test" ]
  workflow_dispatch:

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies 
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Jupyter build
        run: jupyter-book build ./literacy.oceanice

      - name: Creation of docs folder
        run: mkdir docs

      - name: Copy content of _build/html in docs
        run: cp -r literacy.oceanice/_build/html/* docs

      - name: Insert CSS corrections in docs/_static/basic.css
        run: cat literacy.oceanice/corrections.css >> docs/_static/basic.css

      - name: Create .nojekyll file
        run: touch docs/.nojekyll

      - name: Upload docs artifact
        uses: actions/upload-pages-artifact@v1
        with:
          name: github-pages
          path: docs

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3