name: Deployment on s4oceanice.eu/demo/

on:
  pull_request:
    branches:
      - main
    types: [closed]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        python-version: ["3.12"]
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies 
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Jupyter build
        run: jupyter-book build ./literacy.oceanice

      - name: Creation of docs folder
        run: mkdir docs

      - name: Copy content of _build/html in docs
        run: cp -r literacy.oceanice/_build/html/* docs

      - name: Insert CSS corrections in docs/_static/basic.css
        run: cat literacy.oceanice/corrections.css >> docs/_static/basic.css

      - name: Create .nojekyll file
        run: touch docs/.nojekyll

      - name: Deploy docs to demo folder
        run: |
          rm -rf /opt/data00/vhosts/s4oceanice.eu/public_html/demo/*
          cp -r docs/* /opt/data00/vhosts/s4oceanice.eu/public_html/demo/
