name: Deployment on literacy.s4oceanice.eu

on:
  pull_request:
    branches:
      - main
    types: [closed]
  workflow_dispatch:

jobs:
  build:
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies 
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Jupyter build
        run: jupyter-book build ./literacy.oceanice

      - name: Creation of docs folder
        run: mkdir docs

      - name: Copy content of _build/html in docs
        run: cp -r literacy.oceanice/_build/html/* docs

      - name: Insert CSS corrections in docs/_static/basic.css
        run: cat literacy.oceanice/corrections.css >> docs/_static/basic.css

      - name: Create .nojekyll file
        run: touch docs/.nojekyll

      - name: Install sshpass
        run: sudo apt-get install sshpass

      - name: Rm old content via ssh
        uses: fifsky/ssh-action@master
        with:
          command: |
            (cd /opt/data00/vhosts/literacy.s4oceanice.eu/public_html && rm -r *)

          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USER }}
          pass: ${{ secrets.SSH_KEY }}
          args: -tt

      - name: Copy files to s4oceanice
        env:
          SSH_KEY: ${{secrets.SSH_KEY}}
        run: sshpass -p $SSH_KEY scp -r -v -o StrictHostKeyChecking=no docs/* literacygithub@literacy.s4oceanice.eu:/opt/data00/vhosts/literacy.s4oceanice.eu/public_html